import '../sass/main.scss';
import '../js/onSearch.js';
import '../js/footer-modal.js';
import '../js/error-search.js';
import '../js/loader.js';
import '../js/saveMoviesOnLocal.js';
import '../js/pagination.js';
import '../js/top-button.js';
import '../js/modal.js';
